version: "3"

# Configure default network as the external one
networks:
  default:
    external:
      name: ${NETWORK_NAME}

# Define volumes
volumes:
  syncthing_data:
    external:
      name: ${SYNCTHING_VOLUME_NAME}

# Declare services
services:
  # Radicale: CalDav and CardDav server
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    volumes:
      - ./conf.d:/etc/radicale/:ro
      - syncthing_data:/var/syncthing
    environment:
      - UID=1000
      - GID=1000
    labels:
      traefik.frontend.rule: "Host:radicale.${MAIN_DOMAIN:-localhost}"
      traefik.port: "5232"
      traefik.enable: "true"
      #### Uncomment this 2 lines to unable https
      # traefik.frontend.redirect.entryPoint: "https"
      # traefik.frontend.entryPoints: "http,https"
    command: radicale --config /etc/radicale/config
    restart: unless-stopped
